//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDH
    {
        public int MA_SP { get; set; }
        public int MA_DH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string TEN_MON { get; set; }
    
        public virtual DON_DAT_HANG DON_DAT_HANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
