//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_DAT_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_DAT_HANG()
        {
            this.CTDHs = new HashSet<CTDH>();
        }
    
        public int MA_DH { get; set; }
        public int MA_KH { get; set; }
        public int MA_NV { get; set; }
        public string DIACHIGIAOHANG { get; set; }
        public Nullable<System.DateTime> NGAY_GIODAT { get; set; }
        public string TRANGTHAI_DH { get; set; }
        public string PT_THANHTOAN { get; set; }
        public decimal ShippingFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDHs { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
