//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOP_Y
    {
        public int MA_GOPY { get; set; }
        public int MA_KH { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
